files: dhl/
repos:
    - repo: meta
      hooks:
        - id: check-hooks-apply

    - repo: pre-commit
      hooks:
        - id: debug-statements

    - repo: black
      hooks:
          - id: black
            language_version: python3.9
            args: [--line-length=79, --check, ./dhl, ./tests]

    - repo: flake8
      hooks:
        - id: flake8

    - repo: bandit
      hooks:
        - id: bandit
          args: [ -v, -r, ./dhl, ./tests ]

    - repo: local
      hooks:
        - id: pytest-check
          name: pytest-check
          entry: pytest
          language: system
          pass_filenames: false
          always_run: true
