[tool.black]
line-length = 120
target-version = ["py39"]
paths = ["dhl", "tests"]

[tool.vulture]
ignore_names = ["context", "*_mock"]
make_whitelist = true
min_confidence = 80
paths = ["dhl", "tests"]
sort_by_size = true
